USE Pilates;

CREATE TABLE Aparelhos
(
    AparelhoId UNIQUEIDENTIFIER PRIMARY KEY,
    Descricao VARCHAR(80) not NULL
);

CREATE TABLE Exercicios
(
    ExercicioId UNIQUEIDENTIFIER PRIMARY KEY,
    Descricao VARCHAR(80) not null,
    AparelhoId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Aparelhos
);

CREATE TABLE Modalidades
(
    ModalidadeId UNIQUEIDENTIFIER PRIMARY KEY,
    Descricao VARCHAR(80) NOT NULL,
);

CREATE TABLE Cidades
(
    CidadeId UNIQUEIDENTIFIER PRIMARY KEY,
    Descricao VARCHAR(80) NOT NULL,
    Estado VARCHAR(80) NOT NULL,
    Cep VARCHAR(20) NOT NULL
);

CREATE TABLE Enderecos
(
    EnderecoId UNIQUEIDENTIFIER PRIMARY KEY,
    Logradouro VARCHAR(80) NOT NULL,
    Numero VARCHAR(10) NOT NULL,
    Complemento VARCHAR(80),
    Bairro VARCHAR(80) NOT NULL,
    CidadeId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Cidades
);

CREATE TABLE Salas
(
    SalaId UNIQUEIDENTIFIER PRIMARY KEY,
    Descricao VARCHAR(80) NOT NULL
);

CREATE TABLE Especialidades
(
    EspecialidadeId UNIQUEIDENTIFIER PRIMARY KEY,
    Descricao VARCHAR(80)
);

CREATE TABLE FormasPagamentos
(
    FormaPagamentoId UNIQUEIDENTIFIER PRIMARY KEY,
    Descricao VARCHAR(80)
);

CREATE TABLE Professores
(
    ProfessorId UNIQUEIDENTIFIER PRIMARY KEY,
    EspecialidadeId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Especialidades,
    EnderecoId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Enderecos,
    Nome VARCHAR(80) NOT NULL,
    DataNascimento DATETIME NOT NULL,
    Sexo VARCHAR(10) NOT NULL,
    Cpf VARCHAR(14) NOT NULL UNIQUE,
    /*999.999.999-99*/
    Rg VARCHAR(20) NOT NULL,
    Email VARCHAR(80),
    Celular VARCHAR(14) NOT null,
    /*(99)99999-9999*/
    Telefone VARCHAR(13)
    /*(99)9999-9999*/
);

CREATE table Alunos
(
    AlunoId UNIQUEIDENTIFIER PRIMARY KEY,
    NomeResponsavel VARCHAR(80),
    ComoConheceu VARCHAR(100),
    EnderecoId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Enderecos,
    Nome VARCHAR(80) NOT NULL,
    DataNascimento DATETIME NOT NULL,
    Sexo VARCHAR(10) NOT NULL,
    Cpf VARCHAR(14) NOT NULL UNIQUE,
    /*999.999.999-99*/
    Rg VARCHAR(20) NOT NULL,
    Email VARCHAR(80),
    Celular VARCHAR(14) NOT null,
    /*(99)99999-9999*/
    Telefone VARCHAR(13)
    /*(99)9999-9999*/
);

CREATE TABLE Aulas
(
    AulaId UNIQUEIDENTIFIER PRIMARY KEY,
    Descricao VARCHAR(80) NOT NULL,
    ExercicioId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Exercicios,
    ModalidadeId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Modalidades,
    ProfessorId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Professores,
);

CREATE TABLE Matriculas
(
    MatriculalId UNIQUEIDENTIFIER PRIMARY KEY,
    ValorMatricula DECIMAL(9,2) NOT NULL,
    DataVencimentoMatricula DATETIME NOT NULL,
    ValorMensalidade DECIMAL(9,2) NOT NULL,
    DataVencimentoMensalidade DATETIME NOT NULL,
    SalaId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Salas,
    FormaPagamentoId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES FormasPagamentos,
    AlunoId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Alunos,
    AulaId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Aulas,
);

CREATE TABLE ContasPagar(
    ContasPagarId UNIQUEIDENTIFIER PRIMARY KEY,
    StatusPagamento VARCHAR(3), /*Sim ou Não*/
    Liberado VARCHAR(3),/*Sim ou Não*/
    MatriculaId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Matriculas
);

CREATE TABLE Agendas(
    AgendaId UNIQUEIDENTIFIER PRIMARY KEY,
    DataAula DATETIME NOT NULL,
    DiaDisponivel VARCHAR(3),/*Sim ou Não*/
    AulaId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Aulas,
    ProfessorId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Professores,
);